name: Build PGO wheel
description: Builds a PGO-optimized wheel for monty-python

inputs:
  interpreter:
    description: 'Interpreter(s) to build the wheel for'
    required: true
  rust-toolchain:
    description: 'Rust toolchain to use'
    required: true

outputs:
  wheel-dir:
    description: 'Path to the directory containing built wheels'
    value: ${{ steps.find_wheel.outputs.dir }}

runs:
  using: "composite"
  steps:
    - name: prepare profiling directory
      shell: bash
      run: mkdir -p ${{ github.workspace }}/profdata

    - name: build initial wheel (instrumented)
      uses: PyO3/maturin-action@v1
      with:
        manylinux: auto
        args: >
          --release
          --out pgo-wheel
          --interpreter 3.12
        rust-toolchain: ${{ inputs.rust-toolchain }}
        docker-options: -e CI
        working-directory: crates/monty-python
      env:
        RUSTFLAGS: '-Cprofile-generate=${{ github.workspace }}/profdata'

    - name: detect rust host
      run: echo RUST_HOST=$(rustc -Vv | grep host | cut -d ' ' -f 2) >> "$GITHUB_ENV"
      shell: bash

    - name: generate pgo data
      run: |
        pip install pydantic-monty --no-index --no-deps --find-links pgo-wheel --force-reinstall
        python exercise.py
        rustup run ${{ inputs.rust-toolchain }} bash -c 'echo LLVM_PROFDATA=$RUSTUP_HOME/toolchains/$RUSTUP_TOOLCHAIN/lib/rustlib/$RUST_HOST/bin/llvm-profdata >> "$GITHUB_ENV"'
      shell: bash
      working-directory: crates/monty-python

    - name: merge pgo data
      # PowerShell handles paths on Windows better, and works well enough on Unix
      run: ${{ env.LLVM_PROFDATA }} merge -o ${{ github.workspace }}/merged.profdata ${{ github.workspace }}/profdata
      shell: pwsh

    - name: build pgo-optimized wheel
      uses: PyO3/maturin-action@v1
      with:
        manylinux: auto
        args: >
          --release
          --out dist
          --interpreter ${{ inputs.interpreter }}
        rust-toolchain: ${{ inputs.rust-toolchain }}
        docker-options: -e CI
        working-directory: crates/monty-python
      env:
        RUSTFLAGS: '-Cprofile-use=${{ github.workspace }}/merged.profdata'

    - name: find built wheels
      id: find_wheel
      run: echo "dir=crates/monty-python/dist" >> "$GITHUB_OUTPUT"
      shell: bash
